### ISSUE TITLE
Clarify instructions

### ISSUE THREAD

**Issue by maro-21** [Zaczero/osm-revert#10]
Text "Auto-discussion (optional): (?)" needs to be changed.

I didn't know what it meant, I thought the tool would add a tag to the changeset with a link to this discussion, but it flooded the user changesets, which was not my intention :/.

https://www.openstreetmap.org/user/Kokp18/history

**Comment by Zaczero** [comment]
There is also a hint tooltip on the (?) which says: Discussion on the reverted changesets. I would be happy to change it if you guide me in the right direction. I want the text to be short and this is the best I've been able to come up with. In OSM, discussions are conversations under changesets.

**Comment by Zaczero** [comment]
Also please notice the placeholder text which suggest: I reverted this changeset because...

**Comment by Zaczero** [comment]
Maybe the tooltip could be changed to something like this: Comment on each of the reverted changesets

**Comment by maro-21** [comment]
Verbs are missing.

My suggestions:
- change the tooltip from `Discussion on the reverted changesets` to e.g. `This text will be added on all the reverted changesets`
- change `Auto-discussion (optional):`, but I don't have ideas now for a better text which will be short

**Comment by Zaczero** [comment]
I proceeded with "Comment on each of the reverted changesets", as I believe it's a little clearer than "This text will be added on all the reverted changesets".
