### ISSUE TITLE
Url scheme for forwarding the ids of changesets

### ISSUE THREAD

**Issue by deevroman** [Zaczero/osm-revert#14]
Now the changesets have to be entered manually. It would be convenient to have autocompletion from url parameters, like `revert.monicz.dev?changesets_ids=123,456,...`

This would be useful to integrate the reverter with userscripts in osmcha.org. Or in the extension https://addons.mozilla.org/ru/firefox/addon/jumptoosmchangesetanalyzer

**Comment by Zaczero** [comment]
This is actually supported but there is no proper documentation for it:

https://revert.monicz.dev/?changesets=123,456&query-filter=abc

**Comment by Zaczero** [comment]
Related code

https://github.com/Zaczero/osm-revert/blob/eb7b64b2b66c694068f17577fdf51f0e5ab0b7d9/web/templates/authorized.jinja2#L23

**Comment by Zaczero** [comment]
Integration documentation is now available on the osm wiki:
https://wiki.openstreetmap.org/wiki/Osm-revert#External_integration
