### ISSUE TITLE
Revert failed.

### ISSUE THREAD

**Issue by maraf24** [Zaczero/osm-revert#2]
Dla zestawu 127128622 generuje błąd:
![image](https://user-images.githubusercontent.com/10471006/211420884-78bd4489-7faa-4923-851b-f6015ed1a4ae.png)

**Comment by Zaczero** [comment]
Poprawione, niepoprawnie obsługiwało przypadek w którym użytkownik zmodyfikował element, który aktualnie jest już usunięty. W takim przypadku aplikacja pominie revert na danym elemencie (który aktualnie jest już usunięty i nie został on usunięty w danym zestawie).

**Comment by maraf24** [comment]
Dzięki, w końcu wygodnie wycofałem złe zmiany z tego zestawu 😄
