### ISSUE TITLE
Warn user when comment is too long

### ISSUE THREAD

**Issue by dreua** [Zaczero/osm-revert#21]
`🚧 Warning: Trimming comment value because it exceeds 255 characters`

Thats good to know but after clicking "revert and upload" I can't do anything about it, can I? In this case it just cropped the end of a URL which luckily wasn't significant, but otherwise it would be great to know that before submitting the change. Maybe a "dry run" in general would be a good idea to catch any errors before submitting the whole thing. (I shall try the "revert and download .osc" next time albeit having no clue what that file extension is.)

Apart from this nitpicking everything works great, thank you so much for the useful tool! :heart:

**Comment by Zaczero** [comment]
Resolved — I have added a small X-inspired char counter

### Default view

![image](https://github.com/Zaczero/osm-revert/assets/10835147/b0c14a85-ea1a-44f9-a7f7-57479f09fa83)

### ≤ 100 chars left

![image](https://github.com/Zaczero/osm-revert/assets/10835147/4abb771e-0ed1-45cd-bbf4-941f2b088f08)

### ≤ 20 chars left

![image](https://github.com/Zaczero/osm-revert/assets/10835147/ed51ebfb-05ea-4c81-966c-66807408da7f)

**Comment by dreua** [comment]
Wow that is an astonishingly fast and complete solution! Thank you! :100:
