### ISSUE TITLE
In what order to revert?

### ISSUE THREAD

**Issue by maro-21** [Zaczero/osm-revert#28]
Suppose a new user added 20 objects and edited 10 existing objects. Then in a second changeset, they changed something else in those 30 objects. In what order should I undo the changes so that this tool can restore the state before these two edits?

**Comment by Zaczero** [comment]
For the best results, the changesets should be reverted from most recent to least recent (from highest number to lowest number). If you pass more than 1 changeset at a time to osm-revert, it will automatically sort it for you. You will only need to sort it manually if you need to perform multiple distinct reverts. If the order is not correct, there is still a very high chance that everything will be resolved automatically (but there is a small chance it will not). On failed resolutions you will receive an information message like: "Please verify: object link".
