### ISSUE TITLE
Suggestion: always mention the number(s) of the reverted changeset(s)

### ISSUE THREAD

**Issue by 501Ghost** [Zaczero/osm-revert#3]
I think that the changeset number(s) of the reverted changeset(s) should always be included in the changeset comment or in a separate changeset tag. Is this something that this tool can enforce?

**Comment by Zaczero** [comment]
This is already a thing - `revert:ids` is included.

**Comment by 501Ghost** [comment]
I hadn't noticed that. Thank you for the clarification. Have a good day.
