### ISSUE TITLE
Exit code 254 

### ISSUE THREAD

**Issue by MikeTho16** [Zaczero/osm-revert#30]
Attempted to rever changeset 149739087

```
 🔒️ Logging in to OpenStreetMap
 👤 Welcome, tekim!
 ☁️ Downloading changeset 149739087
 [1/?] OpenStreetMap …
 [1/1] OpenStreetMap: 0 element
 🔁 Generating a revert
 🏁 Total time: 0.2 sec
 Exit code: 254
```

I later realized that this is an empty changeset (didn't even think that was possible), and I presume that is the reason for the Exit code, however, it would be nice to have a message explaining that the user attempted to revert an empty changeset (if that is the reason for the exit code)

**Comment by Zaczero** [comment]
Fixed

![image](https://github.com/Zaczero/osm-revert/assets/10835147/a7f3d27c-398b-41be-9aef-c3713a671b73)

**Comment by MikeTho16** [comment]
Thanks for the quick fix!
