### ISSUE TITLE
Stops responding part way through reversion

### ISSUE THREAD

**Issue by Fizzie41** [Zaczero/osm-revert#35]
Hi.

I know you're flat out with NG, but I'm trying to revert https://www.openstreetmap.org/changeset/124750619

Shows:

[1/343] OpenStreetMap: 726 elements
[2/343] Overpass (342 partitions, this may take a while) …

gets to

[210/343] Partition #209: OK

then just stops running.

No error messages, nothing?

CS in question added 726 nodes, each only of an apartment building with a name included, so it shouldn't be reaching a rate limit at all.

Have tried it as both "Forcefully remove conflicting elements" & also "Skip conflicting elements (assume they were fixed) " but both have exactly the same result.

Have also tried 2-3 times over a week or so, but same result each time.

Any thoughts?

**Comment by Zaczero** [comment]
The 5 minute timeout handling was messed up. I reworked it and bumped it to 30 minutes. I'll close this issue when the update is finished uploading to the server :+1: Thanks!

**Comment by Zaczero** [comment]
![image](https://github.com/user-attachments/assets/c0f0cbcc-aedb-4ea3-8cfb-419f7dc1405f)
