### ISSUE TITLE
Too many simultaneous connections

### ISSUE THREAD

**Issue by Fizzie41** [Zaczero/osm-revert#36]
Further problem since raising the other issue earlier!

When going to do another reversion I got this:

![Reverter](https://github.com/user-attachments/assets/2f641e43-fbb3-495f-b617-e7c791d047b7)

Have tried logging out then back in, restarting the laptop & clearing the cache, but no change?

Wondering if it's connected in any way with the other issue?

Thanks!

**Comment by Zaczero** [comment]
The 5 minute timeout handling was messed up. I reworked it and bumped it to 30 minutes. I'll close this issue when the update is finished uploading to the server :+1: Thanks!
