### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by Mashin6** [Zaczero/osm-revert#4]
What about adding more filtering options e.g. to revert only objects that have a certain tag? 
Syntax could be similar to Overpass. `way[golf=cart_path]` or `wr[water~"river|lake"]`

**Comment by Zaczero** [comment]
I agree! And you should be able to exclude by using for example `-way`.

**Comment by Zaczero** [comment]
![image](https://user-images.githubusercontent.com/10835147/213903330-5dacd31b-c783-4a4e-a72a-4edcef4aaaa8.png)

Done
