### ISSUE TITLE
Add option to automatically comment on reverted changesets

### ISSUE THREAD

**Issue by Kovoschiz** [Zaczero/osm-revert#5]
New feature request: Similar to those DWG revert comments to notify user and show an easily seen public record on each changeset. To reduce repetitiveness and annoyance, it should be selectable for all, newest, or oldest changeset reverted in each job. Message ideally customizable somehow.

**Comment by Zaczero** [comment]
I love this idea!

**Comment by Zaczero** [comment]
![image](https://user-images.githubusercontent.com/10835147/234362840-1ab9d95c-6ff4-473a-985f-cc8272cb3dc0.png)

Added :+1:
