### ISSUE TITLE
Better support for mobile devices

### ISSUE THREAD

**Issue by mxxcon** [Zaczero/osm-revert#9]
The UI on mobile is generally good, but some elements are too small to read without zooming in. This is especially true of text labels and buttons.
![Screenshot_20230426_164511_Samsung Internet](https://user-images.githubusercontent.com/847140/234699048-3c25e62e-46d3-4a59-b625-e7858985ce08.png)

**Comment by Zaczero** [comment]
![2023-08-17_01-40-15](https://github.com/Zaczero/osm-revert/assets/10835147/707a2cf4-b597-44e6-b831-aeacd30167ff)

The new interface is mobile-friendly, marking as resolved :slightly_smiling_face:.
